version: 2

sources:
    - name: staging
      database: data-eng-zoomcamp-339102
      schema: trips_data_all

      tables:
        - name: green_tripdata_partitoned
        - name: yellow_tripdata_partitoned



